version: '3.8'
services:
  api:
    build: .
    ports:
      - "80:80"
    environment:
      - ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3